#!/usr/bin/sh

exec stack ghc --       \
    --make xmonad.hs    \
    -i                  \
    -ilib               \
    -fforce-recomp      \
    -main-is main       \
    -v0                 \
    -Wall               \
    -fwarn-tabs         \
    -O2                 \
    -threaded           \
    -with-rtsopts=-N4   \
	-o "$1"

[ -f /usr/bin/xmonad ] && sudo rm /usr/bin/xmonad
#[ -f /usr/bin/xmobar ] && sudo rm /usr/bin/xmobar
ARCH=$(uname -m)
sudo cp xmonad-$ARCH-linux /usr/bin/xmonad

