name: xmonad-ntrx
version: 0.9.0
synopsis: my custom xmonad settings
homepage: https://github.com/neoterux/dotfiles
github: neoterux/xmonad-config
author: Luis Bajaña
maintainer: labfernandez2014@gmail.com

dependencies:
  - X11
  - base
  - containers
  - xmonad
  - xmonad-contrib
  - xmobar
  - netlink

executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
