resolver: nightly-2022-01-04
  # url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/15.yaml

packages:
- ./
- xmonad
- xmonad-contrib
- xmobar

extra-deps:
  - netlink-1.1.1.0
    # - X11-1.10.2@sha256:5f449203afe0240ca5124dc4b28d906fbde1d56a15c0c95534f677060f8b72ac,3747
    # - X11-1.10.2

flags:
  xmobar:
    with_xft: true
    with_threaded: true
    with_dbus: true
    with_utf8: true
    with_xpm: true

arch: x86_64

  #resolver:
  #  compiler: ghc-8.10.7
